### ISSUE TITLE
插件在1.20.1paper使用时会莫名报错

### ISSUE THREAD

**Issue by Mxmilu666** [handy-git/monster#1]
paper版本:Paper version git-Paper-81 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: fe780d0)
报错内容:
[08:52:14 ERROR]: Could not pass event CreatureSpawnEvent to monster v3.0.6
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:322) ~[?:?]
        at cn.handyplus.monster.util.MonsterEquipmentUtil.setEquipment(MonsterEquipmentUtil.java:50) ~[Monster-3.0.6.jar:?]
        at cn.handyplus.monster.util.MonsterEquipmentUtil.lotteryEquipment(MonsterEquipmentUtil.java:341) ~[Monster-3.0.6.jar:?]
        at cn.handyplus.monster.spawn.SixteenCreatureSpawn.setCreatureSpawn(SixteenCreatureSpawn.java:66) ~[Monster-3.0.6.jar:?]
        at cn.handyplus.monster.spawn.SixteenCreatureSpawn.setCreatureSpawn(SixteenCreatureSpawn.java:25) ~[Monster-3.0.6.jar:?]
        at cn.handyplus.monster.listener.MonsterListener.onCreatureSpawnEvent(MonsterListener.java:70) ~[Monster-3.0.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor387.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-81]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-81]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:761) ~[paper-1.20.1.jar:git-Paper-81]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:666) ~[paper-1.20.1.jar:git-Paper-81]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1656) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1564) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:298) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:214) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:184) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:616) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:499) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:827) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1557) ~[paper-1.20.1.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
       基本上是几秒报错一次

**Comment by Mxmilu666** [comment]
另外正常使用没问题
没有别的同类性质修改怪物的插件

**Comment by handy-git** [comment]
3.0.7 已修复
